#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IOS_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${IOS_ROOT}/.." && pwd)"
DESIGN_PATH="${REPO_ROOT}/docs/ios-guide/DESIGN.md"
OUTPUT_PATH="${1:-${IOS_ROOT}/Packages/DesignSystem/Sources/DesignSystem/Theme.swift}"

python3 - "${DESIGN_PATH}" "${OUTPUT_PATH}" <<'PY'
import re
import sys
from pathlib import Path

design_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])
design = design_path.read_text()

if "#47E7B0" not in design:
    raise SystemExit("DESIGN.md is missing canonical brand green #47E7B0")
retired_green = "#" + "3D" + "9B2F"
if retired_green in design.split("## Brand", 1)[-1].split("---", 1)[0]:
    raise SystemExit("Retired green appears in active design tokens")

def color(token: str) -> str:
    match = re.search(rf"\|\s*`{re.escape(token)}`\s*\|\s*`(#[0-9A-Fa-f]{{6}})`", design)
    if not match:
        raise SystemExit(f"Missing color token: {token}")
    return match.group(1).upper()

def number(token: str, section: str) -> str:
    section_text = design.split(f"## {section}", 1)[1].split("\n---", 1)[0]
    match = re.search(rf"\|\s*`{re.escape(token)}`\s*\|\s*([0-9.]+)", section_text)
    if not match:
        raise SystemExit(f"Missing {section.lower()} token: {token}")
    return match.group(1)

def motion(token: str) -> str:
    match = re.search(rf"\|\s*`motion\.{re.escape(token)}`\s*\|\s*([0-9]+)", design)
    if not match:
        raise SystemExit(f"Missing motion token: {token}")
    return str(int(match.group(1)) / 1000).rstrip("0").rstrip(".")

tokens = {
    "primary_orange": color("color.primary.orange"),
    "primary_green": color("color.primary.green"),
    "primary_accent": color("color.primary.accent"),
    "bg_base": color("color.bg.base"),
    "bg_surface": color("color.bg.surface"),
    "bg_elevated": color("color.bg.elevated"),
    "bg_border": color("color.bg.border"),
    "bg_border_soft": color("color.bg.borderSoft"),
    "text_primary": color("color.text.primary"),
    "text_body": color("color.text.body"),
    "text_secondary": color("color.text.secondary"),
    "text_muted": color("color.text.muted"),
    "text_disabled": color("color.text.disabled"),
    "text_on_dark": color("color.text.onDark"),
    "text_on_dark_muted": color("color.text.onDarkMuted"),
    "semantic_success": color("color.semantic.success"),
    "semantic_warning": color("color.semantic.warning"),
    "semantic_error": color("color.semantic.error"),
    "semantic_info": color("color.semantic.info"),
    "semantic_premium": color("color.semantic.premium"),
    "macro_protein": color("color.macro.protein"),
    "macro_carbs": color("color.macro.carbs"),
    "macro_fat": color("color.macro.fat"),
    "macro_calories": color("color.macro.calories"),
    "space_xs": number("space.xs", "Spacing"),
    "space_sm": number("space.sm", "Spacing"),
    "space_md": number("space.md", "Spacing"),
    "space_lg": number("space.lg", "Spacing"),
    "space_xl": number("space.xl", "Spacing"),
    "space_2xl": number("space.2xl", "Spacing"),
    "space_3xl": number("space.3xl", "Spacing"),
    "space_4xl": number("space.4xl", "Spacing"),
    "radius_sm": number("radius.sm", "Radii"),
    "radius_md": number("radius.md", "Radii"),
    "radius_lg": number("radius.lg", "Radii"),
    "radius_xl": number("radius.xl", "Radii"),
    "radius_pill": number("radius.pill", "Radii"),
    "motion_button": motion("button"),
    "motion_card": motion("card"),
    "motion_fade": motion("fade"),
    "motion_count": motion("count"),
    "motion_pulse": motion("pulse"),
}

swift = f'''// Generated by ios/scripts/generate-theme.sh from docs/ios-guide/DESIGN.md.
// Do not edit by hand.

import SwiftUI

public struct Theme: Equatable, Sendable {{
    public var color: ThemeColor
    public var font: ThemeFont
    public var text: ThemeText
    public var spacing: ThemeSpacing
    public var radius: ThemeRadius
    public var motion: ThemeMotion

    public init(
        color: ThemeColor = .init(),
        font: ThemeFont = .init(),
        text: ThemeText = .init(),
        spacing: ThemeSpacing = .init(),
        radius: ThemeRadius = .init(),
        motion: ThemeMotion = .init()
    ) {{
        self.color = color
        self.font = font
        self.text = text
        self.spacing = spacing
        self.radius = radius
        self.motion = motion
    }}

    public static let app = Theme()
}}

public struct ThemeColor: Equatable, Sendable {{
    public var primary: PrimaryColor
    public var bg: BackgroundColor
    public var text: TextColor
    public var semantic: SemanticColor
    public var macro: MacroColor

    public init(
        primary: PrimaryColor = .init(),
        bg: BackgroundColor = .init(),
        text: TextColor = .init(),
        semantic: SemanticColor = .init(),
        macro: MacroColor = .init()
    ) {{
        self.primary = primary
        self.bg = bg
        self.text = text
        self.semantic = semantic
        self.macro = macro
    }}
}}

public struct PrimaryColor: Equatable, Sendable {{
    public let orange = ThemeColorToken(hex: "{tokens["primary_orange"]}")
    public let green = ThemeColorToken(hex: "{tokens["primary_green"]}")
    public let accent = ThemeColorToken(hex: "{tokens["primary_accent"]}")

    public init() {{}}
}}

public struct BackgroundColor: Equatable, Sendable {{
    public let base = ThemeColorToken(hex: "{tokens["bg_base"]}")
    public let surface = ThemeColorToken(hex: "{tokens["bg_surface"]}")
    public let elevated = ThemeColorToken(hex: "{tokens["bg_elevated"]}")
    public let border = ThemeColorToken(hex: "{tokens["bg_border"]}")
    public let borderSoft = ThemeColorToken(hex: "{tokens["bg_border_soft"]}")

    public init() {{}}
}}

public struct TextColor: Equatable, Sendable {{
    public let primary = ThemeColorToken(hex: "{tokens["text_primary"]}")
    public let body = ThemeColorToken(hex: "{tokens["text_body"]}")
    public let secondary = ThemeColorToken(hex: "{tokens["text_secondary"]}")
    public let muted = ThemeColorToken(hex: "{tokens["text_muted"]}")
    public let disabled = ThemeColorToken(hex: "{tokens["text_disabled"]}")
    public let onDark = ThemeColorToken(hex: "{tokens["text_on_dark"]}")
    public let onDarkMuted = ThemeColorToken(hex: "{tokens["text_on_dark_muted"]}")

    public init() {{}}
}}

public struct SemanticColor: Equatable, Sendable {{
    public let success = ThemeColorToken(hex: "{tokens["semantic_success"]}")
    public let warning = ThemeColorToken(hex: "{tokens["semantic_warning"]}")
    public let error = ThemeColorToken(hex: "{tokens["semantic_error"]}")
    public let info = ThemeColorToken(hex: "{tokens["semantic_info"]}")
    public let premium = ThemeColorToken(hex: "{tokens["semantic_premium"]}")

    public init() {{}}
}}

public struct MacroColor: Equatable, Sendable {{
    public let protein = ThemeColorToken(hex: "{tokens["macro_protein"]}")
    public let carbs = ThemeColorToken(hex: "{tokens["macro_carbs"]}")
    public let fat = ThemeColorToken(hex: "{tokens["macro_fat"]}")
    public let calories = ThemeColorToken(hex: "{tokens["macro_calories"]}")

    public init() {{}}
}}

public struct ThemeFont: Equatable, Sendable {{
    public let display = "Outfit"
    public let body = "Inter"
    public let numeric = "DM Sans"

    public init() {{}}
}}

public struct ThemeText: Equatable, Sendable {{
    public let caption = TextStyle(size: 12, lineHeight: 16, tracking: 0)
    public let bodySM = TextStyle(size: 14, lineHeight: 20, tracking: 0)
    public let body = TextStyle(size: 16, lineHeight: 24, tracking: 0)
    public let bodyLG = TextStyle(size: 18, lineHeight: 26, tracking: 0)
    public let titleSM = TextStyle(size: 20, lineHeight: 26, tracking: -0.2)
    public let title = TextStyle(size: 22, lineHeight: 28, tracking: -0.2)
    public let titleLG = TextStyle(size: 28, lineHeight: 34, tracking: -0.4)
    public let display = TextStyle(size: 32, lineHeight: 38, tracking: -0.6)

    public init() {{}}
}}

public struct TextStyle: Equatable, Sendable {{
    public let size: CGFloat
    public let lineHeight: CGFloat
    public let tracking: CGFloat

    public init(size: CGFloat, lineHeight: CGFloat, tracking: CGFloat) {{
        self.size = size
        self.lineHeight = lineHeight
        self.tracking = tracking
    }}
}}

public struct ThemeSpacing: Equatable, Sendable {{
    public let xs: CGFloat = {tokens["space_xs"]}
    public let sm: CGFloat = {tokens["space_sm"]}
    public let md: CGFloat = {tokens["space_md"]}
    public let lg: CGFloat = {tokens["space_lg"]}
    public let xl: CGFloat = {tokens["space_xl"]}
    public let twoXL: CGFloat = {tokens["space_2xl"]}
    public let threeXL: CGFloat = {tokens["space_3xl"]}
    public let fourXL: CGFloat = {tokens["space_4xl"]}

    public init() {{}}
}}

public struct ThemeRadius: Equatable, Sendable {{
    public let sm: CGFloat = {tokens["radius_sm"]}
    public let md: CGFloat = {tokens["radius_md"]}
    public let lg: CGFloat = {tokens["radius_lg"]}
    public let xl: CGFloat = {tokens["radius_xl"]}
    public let pill: CGFloat = {tokens["radius_pill"]}

    public init() {{}}
}}

public struct ThemeMotion: Equatable, Sendable {{
    public let button: Double = {tokens["motion_button"]}
    public let card: Double = {tokens["motion_card"]}
    public let fade: Double = {tokens["motion_fade"]}
    public let count: Double = {tokens["motion_count"]}
    public let pulse: Double = {tokens["motion_pulse"]}

    public init() {{}}
}}

extension EnvironmentValues {{
    public var theme: Theme {{
        get {{ self[ThemeEnvironmentKey.self] }}
        set {{ self[ThemeEnvironmentKey.self] = newValue }}
    }}
}}

private enum ThemeEnvironmentKey: EnvironmentKey {{
    static let defaultValue = Theme.app
}}

public struct ThemeColorToken: Equatable, Sendable {{
    public let hex: String

    public init(hex: String) {{
        self.hex = hex
    }}

    public var color: Color {{
        let value = self.hex.trimmingCharacters(in: CharacterSet(charactersIn: "#"))
        var number: UInt64 = 0
        Scanner(string: value).scanHexInt64(&number)

        let red = Double((number >> 16) & 0xff) / 255
        let green = Double((number >> 8) & 0xff) / 255
        let blue = Double(number & 0xff) / 255

        return Color(.sRGB, red: red, green: green, blue: blue, opacity: 1)
    }}
}}
'''

output_path.parent.mkdir(parents=True, exist_ok=True)
output_path.write_text(swift)
PY
