project_id = "fuelwell"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[studio]
enabled = true

[auth]
enabled = true
site_url = "fuelwell://auth"
additional_redirect_urls = ["fuelwell://auth/callback"]

[storage]
enabled = true
