// Generated by ios/scripts/generate-theme.sh from docs/ios-guide/DESIGN.md.
// Do not edit by hand.

import SwiftUI

public struct Theme: Equatable, Sendable {
    public var color: ThemeColor
    public var font: ThemeFont
    public var text: ThemeText
    public var spacing: ThemeSpacing
    public var radius: ThemeRadius
    public var motion: ThemeMotion

    public init(
        color: ThemeColor = .init(),
        font: ThemeFont = .init(),
        text: ThemeText = .init(),
        spacing: ThemeSpacing = .init(),
        radius: ThemeRadius = .init(),
        motion: ThemeMotion = .init()
    ) {
        self.color = color
        self.font = font
        self.text = text
        self.spacing = spacing
        self.radius = radius
        self.motion = motion
    }

    public static let app = Theme()
}

public struct ThemeColor: Equatable, Sendable {
    public var primary: PrimaryColor
    public var bg: BackgroundColor
    public var text: TextColor
    public var semantic: SemanticColor
    public var macro: MacroColor

    public init(
        primary: PrimaryColor = .init(),
        bg: BackgroundColor = .init(),
        text: TextColor = .init(),
        semantic: SemanticColor = .init(),
        macro: MacroColor = .init()
    ) {
        self.primary = primary
        self.bg = bg
        self.text = text
        self.semantic = semantic
        self.macro = macro
    }
}

public struct PrimaryColor: Equatable, Sendable {
    public let orange = ThemeColorToken(hex: "#E87A1D")
    public let green = ThemeColorToken(hex: "#47E7B0")
    public let accent = ThemeColorToken(hex: "#00D278")

    public init() {}
}

public struct BackgroundColor: Equatable, Sendable {
    public let base = ThemeColorToken(hex: "#F4F5F7")
    public let surface = ThemeColorToken(hex: "#FFFFFF")
    public let elevated = ThemeColorToken(hex: "#0F1117")
    public let border = ThemeColorToken(hex: "#E5E7EB")
    public let borderSoft = ThemeColorToken(hex: "#EEF0F3")

    public init() {}
}

public struct TextColor: Equatable, Sendable {
    public let primary = ThemeColorToken(hex: "#0A0A0F")
    public let body = ThemeColorToken(hex: "#1F2937")
    public let secondary = ThemeColorToken(hex: "#6B7280")
    public let muted = ThemeColorToken(hex: "#9CA3AF")
    public let disabled = ThemeColorToken(hex: "#C7CCD3")
    public let onDark = ThemeColorToken(hex: "#FFFFFF")
    public let onDarkMuted = ThemeColorToken(hex: "#9AA0AC")

    public init() {}
}

public struct SemanticColor: Equatable, Sendable {
    public let success = ThemeColorToken(hex: "#00D278")
    public let warning = ThemeColorToken(hex: "#F59E0B")
    public let error = ThemeColorToken(hex: "#EF4444")
    public let info = ThemeColorToken(hex: "#00B4D8")
    public let premium = ThemeColorToken(hex: "#A855F7")

    public init() {}
}

public struct MacroColor: Equatable, Sendable {
    public let protein = ThemeColorToken(hex: "#00D278")
    public let carbs = ThemeColorToken(hex: "#F59E0B")
    public let fat = ThemeColorToken(hex: "#A855F7")
    public let calories = ThemeColorToken(hex: "#00D278")

    public init() {}
}

public struct ThemeFont: Equatable, Sendable {
    public let display = "Outfit"
    public let body = "Inter"
    public let numeric = "DM Sans"

    public init() {}
}

public struct ThemeText: Equatable, Sendable {
    public let caption = TextStyle(size: 12, lineHeight: 16, tracking: 0)
    public let bodySM = TextStyle(size: 14, lineHeight: 20, tracking: 0)
    public let body = TextStyle(size: 16, lineHeight: 24, tracking: 0)
    public let bodyLG = TextStyle(size: 18, lineHeight: 26, tracking: 0)
    public let titleSM = TextStyle(size: 20, lineHeight: 26, tracking: -0.2)
    public let title = TextStyle(size: 22, lineHeight: 28, tracking: -0.2)
    public let titleLG = TextStyle(size: 28, lineHeight: 34, tracking: -0.4)
    public let display = TextStyle(size: 32, lineHeight: 38, tracking: -0.6)

    public init() {}
}

public struct TextStyle: Equatable, Sendable {
    public let size: CGFloat
    public let lineHeight: CGFloat
    public let tracking: CGFloat

    public init(size: CGFloat, lineHeight: CGFloat, tracking: CGFloat) {
        self.size = size
        self.lineHeight = lineHeight
        self.tracking = tracking
    }
}

public struct ThemeSpacing: Equatable, Sendable {
    public let xs: CGFloat = 4
    public let sm: CGFloat = 8
    public let md: CGFloat = 16
    public let lg: CGFloat = 24
    public let xl: CGFloat = 32
    public let twoXL: CGFloat = 48
    public let threeXL: CGFloat = 64
    public let fourXL: CGFloat = 96

    public init() {}
}

public struct ThemeRadius: Equatable, Sendable {
    public let sm: CGFloat = 6
    public let md: CGFloat = 12
    public let lg: CGFloat = 20
    public let xl: CGFloat = 28
    public let pill: CGFloat = 999

    public init() {}
}

public struct ThemeMotion: Equatable, Sendable {
    public let button: Double = 0.15
    public let card: Double = 0.2
    public let fade: Double = 0.4
    public let count: Double = 0.8
    public let pulse: Double = 0.3

    public init() {}
}

extension EnvironmentValues {
    public var theme: Theme {
        get { self[ThemeEnvironmentKey.self] }
        set { self[ThemeEnvironmentKey.self] = newValue }
    }
}

private enum ThemeEnvironmentKey: EnvironmentKey {
    static let defaultValue = Theme.app
}

public struct ThemeColorToken: Equatable, Sendable {
    public let hex: String

    public init(hex: String) {
        self.hex = hex
    }

    public var color: Color {
        let value = self.hex.trimmingCharacters(in: CharacterSet(charactersIn: "#"))
        var number: UInt64 = 0
        Scanner(string: value).scanHexInt64(&number)

        let red = Double((number >> 16) & 0xff) / 255
        let green = Double((number >> 8) & 0xff) / 255
        let blue = Double(number & 0xff) / 255

        return Color(.sRGB, red: red, green: green, blue: blue, opacity: 1)
    }
}
